linelayer:
    - js_line
    - tr_line

pointlayer:
    - js_point
    - tr_point

linefields:
    - ST_KEY
    - ST_SPT_KEY
    - ST_EPT_KEY
    - ST_SIZE
    - ST_PMATER

pointfields:
    - ST_KEY
    - ST_ATTACHMENT
    - ST_PT_TYPE

attachment:
    - 蝶阀
    - 阀门
    - 闸阀
    - 球阀
    - 调压箱
