server:
    port: 8080
    context-path: #/n

logging:
    config: classpath:logback.xml

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/sttest?characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 3
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    jmx:
        default-domain: stsfm
multipart:
    max-file-size: 10MB
    max-request-size: 10MB

dsl: zlsk_pro_oms,zlsk_pro_ps,zlsk_ps,zlsk_prj_tmykyj
dds: zlsk_pro_oms

zlsk:
    token:
        isCheckToken: false



