line:
-     field: gid
      state: 0
      label: 管线GUID
      type: string
      key: ST_ID
-     field: GXBH
      state: 1
      label: 管线编号
      type: string
      key: ST_KEY
-     field: 起点点号
      state: 1
      label: 起点编号
      type: string
      key: ST_SPT_KEY
-     field: 终点点号
      state: 1
      label: 终点编号
      type: string
      key: ST_EPT_KEY
-     field: 起点埋深
      state: 1
      label: 起点埋深
      type: number
      key: ST_SDEEP
-     field: 终点埋深
      state: 1
      label: 终点埋深
      type: number
      key: ST_EDEEP
-     field: 起点高程
      state: 1
      label: 起点高程
      type: number
      key: ST_SALT
-     field: 终点高程
      state: 1
      label: 终点高程
      type: number
      key: ST_EALT
-     field: 埋设方式
      state: 1
      label: 埋设方式
      type: string
      key: ST_LTTYPE
-     field: 管径
      state: 1
      label: 管径
      type: string
      key: ST_SIZE
-     field: 材质
      state: 1
      label: 材质
      type: string
      key: ST_PMATER
-     field: 流向
      state: 1
      label: 流向
      type: number
      key: ST_FLOWDIR
-     field: 压力值
      state: 1
      label: 压力
      type: string
      key: ST_PRESSUR
-     field: ''
      state: 1
      label: 回路数
      type: string
      key: ST_LOOP_NUM
-     field: ''
      state: 1
      label: 地面位置
      type: string
      key: ST_POSITION
-     field: ''
      state: 1
      label: 断面尺寸
      type: string
      key: ST_SECTION
-     field: ''
      state: 1
      label: 线型
      type: string
      key: ST_LTYPE
-     field: ''
      state: 1
      label: 使用状况
      type: string
      key: ST_STATST
-     field: 压力值
      state: 1
      label: 电压值
      type: string
      key: ST_PSVALUE
-     field: 条数
      state: 1
      label: 电缆条数
      type: string
      key: ST_VENTNUM
-     field: 总孔数
      state: 1
      label: 总孔数
      type: number
      key: ST_HOLETOL
-     field: 已用孔数
      state: 1
      label: 已用孔数
      type: string
      key: ST_HOLESTE
-     field: ''
      state: 1
      label: 电力线间隔
      type: string
      key: ST_ELECTRICAL_DISTANCE
-     field: ''
      state: 1
      label: 模型
      type: string
      key: ST_PMODEL
-     field: 建设日期
      state: 1
      label: 建设年代
      type: string
      key: ST_BD_TIME
-     field: 勘测单位
      state: 1
      label: 权属单位
      type: string
      key: ST_OWNER
-     field: ''
      state: 1
      label: 所在道路
      type: string
      key: ST_ROAD
-     field: ''
      state: 1
      label: 更新状态
      type: string
      key: ST_UPDATE
-     field: ''
      state: 1
      label: 验收证号
      type: string
      key: ST_REC_NUM
-     field: ''
      state: 1
      label: 建设许可证号
      type: string
      key: ST_CHK_NUM
-     field: ''
      state: 1
      label: 工程证号
      type: string
      key: ST_PROJ_NUM
point:
-     field: gid
      state: 0
      label: 管点GUID
      type: string
      key: ST_ID
-     field: 管点编号
      state: 1
      label: 管点编号
      type: string
      key: ST_KEY
-     field: 地面高程
      state: 1
      label: 地面高程
      type: number
      key: ST_PT_ALT
-     field: 特征
      state: 1
      label: 特征
      type: string
      key: ST_PT_TYPE
-     field: 附属物
      state: 1
      label: 附属设施
      type: string
      key: ST_ATTACHMENT
-     field: ''
      state: 1
      label: 偏心井点号
      type: string
      key: ST_OFFSET
-     field: ''
      state: 1
      label: 离心井点号
      type: string
      key: ST_OFFNODE
-     field: 旋转角度
      state: 1
      label: 旋转角度
      type: number
      key: ST_ANGLE
-     field: ''
      state: 1
      label: 地面位置
      type: string
      key: ST_POSITION
-     field: ''
      state: 1
      label: 模型
      type: string
      key: ST_PMODEL
-     field: ''
      state: 1
      label: 井类型
      type: string
      key: ST_WELL
-     field: ''
      state: 1
      label: 井GUID
      type: string
      key: ST_WELL_ID
-     field: ''
      state: 1
      label: 井直径
      type: string
      key: ST_WDIA
-     field: ''
      state: 1
      label: 井脖深
      type: number
      key: ST_NDEEP
-     field: ''
      state: 1
      label: 井底深
      type: number
      key: ST_WDEEP
-     field: 井盖类型
      state: 1
      label: 井盖类型
      type: string
      key: ST_PLATE
-     field: 井盖规格
      state: 1
      label: 井盖规格
      type: string
      key: ST_PSIZE
-     field: 井盖材质
      state: 1
      label: 井盖材质
      type: string
      key: ST_PMATER
-     field: ''
      state: 1
      label: 井材质
      type: string
      key: ST_WMATER
-     field: 建设日期
      state: 1
      label: 建设年代
      type: string
      key: ST_BD_TIME
-     field: 勘测单位
      state: 1
      label: 权属单位
      type: string
      key: ST_OWNER
-     field: 道路名称
      state: 1
      label: 所在道路
      type: string
      key: ST_ROAD
-     field: ''
      state: 1
      label: 档案信息
      type: string
      key: ST_INFO
-     field: ''
      state: 1
      label: 更新状态
      type: string
      key: ST_UPDATE
polygon:
-     field: gid
      state: 0
      label: 管面GUID
      type: number
      key: ST_ID
-     field: ''
      state: 1
      label: 管面编号
      type: number
      key: ST_KEY
-     field: ''
      state: 1
      label: 管面类型
      type: number
      key: ST_ROOM_TYPE
-     field: ''
      state: 1
      label: 更新状态
      type: number
      key: ST_UPDATE
