tables:
-     code: 1000
      name: 政府供电管线
      pipeCode: 1100
      type: line
      key: ZFGD_L
      group: 政府供电
-     code: 1000
      name: 政府供电管点
      pipeCode: 1100
      type: point
      key: ZFGD_P
      group: 政府供电
-     code: 1000
      name: 政府监控管线
      pipeCode: 1700
      type: line
      key: ZFJK_L
      group: 政府监控
-     code: 1000
      name: 政府监控管点
      pipeCode: 1700
      type: point
      key: ZFJK_P
      group: 政府监控
-     code: 3000
      name: 政府给水管线
      pipeCode: 3000
      type: line
      key: ZFJS_L
      group: 政府给水
-     code: 3000
      name: 政府给水管点
      pipeCode: 3000
      type: point
      key: ZFJS_P
      group: 政府给水
-     code: 1000
      name: 政府路灯管线
      pipeCode: 1200
      type: line
      key: ZFLD_L
      group: 政府路灯
-     code: 1000
      name: 政府路灯管点
      pipeCode: 1200
      type: point
      key: ZFLD_P
      group: 政府路灯
-     code: 6000
      name: 政府热力管线
      pipeCode: 6000
      type: line
      key: ZFRL_L
      group: 政府热力
-     code: 6000
      name: 政府热力管点
      pipeCode: 6000
      type: point
      key: ZFRL_P
      group: 政府热力
-     code: 5000
      name: 政府天然气管线
      pipeCode: 5200
      type: line
      key: ZFTR_L
      group: 政府天然气
-     code: 5000
      name: 政府天然气管点
      pipeCode: 5200
      type: point
      key: ZFTR_P
      group: 政府天然气
-     code: 2000
      name: 政府通讯管线
      pipeCode: 2000
      type: line
      key: ZFTX_L
      group: 政府通讯
-     code: 2000
      name: 政府通讯管点
      pipeCode: 2000
      type: point
      key: ZFTX_P
      group: 政府通讯
-     code: 4000
      name: 政府污水管线
      pipeCode: 4200
      type: line
      key: ZFWS_L
      group: 政府污水
-     code: 4000
      name: 政府污水管点
      pipeCode: 4200
      type: point
      key: ZFWS_P
      group: 政府污水
-     code: 4000
      name: 政府雨水管线
      pipeCode: 4100
      type: line
      key: ZFYS_L
      group: 政府雨水
-     code: 4000
      name: 政府雨水管点
      pipeCode: 4100
      type: point
      key: ZFYS_P
      group: 政府雨水
-     code: 1000
      name: 学府供电管线
      pipeCode: 1100
      type: line
      key: GD_LINE
      group: 学府供电
-     code: 1000
      name: 学府供电管点
      pipeCode: 1100
      type: point
      key: GD_POINT
      group: 学府供电
-     code: 3000
      name: 学府给水管线
      pipeCode: 3000
      type: line
      key: JS_LINE
      group: 学府给水
-     code: 3000
      name: 学府给水管点
      pipeCode: 3000
      type: point
      key: JS_POINT
      group: 学府给水
-     code: 1000
      name: 学府路灯管线
      pipeCode: 1200
      type: line
      key: LD_LINE
      group: 学府路灯
-     code: 1000
      name: 学府路灯管点
      pipeCode: 1200
      type: point
      key: LD_POINT
      group: 学府路灯
-     code: 6000
      name: 学府热水管线
      pipeCode: 6200
      type: line
      key: RS_LINE
      group: 学府热水
-     code: 6000
      name: 学府热水管点
      pipeCode: 6200
      type: point
      key: RS_POINT
      group: 学府热水
-     code: 2000
      name: 学府通讯管线
      pipeCode: 2000
      type: line
      key: TX_LINE
      group: 学府通讯
-     code: 2000
      name: 学府通讯管点
      pipeCode: 2000
      type: point
      key: TX_POINT
      group: 学府通讯
-     code: 4000
      name: 学府污水管线
      pipeCode: 4200
      type: line
      key: WS_LINE
      group: 学府污水
-     code: 4000
      name: 学府污水管点
      pipeCode: 4200
      type: point
      key: WS_POINT
      group: 学府污水
-     code: 4000
      name: 学府雨水管线
      pipeCode: 4100
      type: line
      key: YS_LINE
      group: 学府雨水
-     code: 4000
      name: 学府雨水管点
      pipeCode: 4100
      type: point
      key: YS_POINT
      group: 学府雨水
