"use strict";
layui.define([], function(exports) {
    var stBase = sessionStorage.getItem('stBase');
    var stForm = sessionStorage.getItem('stForm');
    var stFlow = sessionStorage.getItem('stFlow');
    var stFlow2 = sessionStorage.getItem('stFlow2');
    var stAuth = sessionStorage.getItem('stAuth');
    var stMap = sessionStorage.getItem('stMap');
    var baseUrl = "http://" + window.location.host;
    var constantUrl = {
        baseTempUrl:baseUrl + '/' + 'STSfm/temp/',
        commonField:{
            FILE_SPLITTER:'FILE_SPLITTER'
        },
        other:{
            bdLocation:'http://api.map.baidu.com/reverse_geocoding/v3/?ak=ySbUZzsD8ge77nlb0IWyf7TLfVsOESVM&output=json&coordtype=wgs84ll&extensions_poi=1&extensions_road=true&location=',
            bdLocationGeoCoding:'http://api.map.baidu.com/geocoding/v3/?output=json&ak=ySbUZzsD8ge77nlb0IWyf7TLfVsOESVM&address=',
            geoserverWmts:'http://192.168.2.163:8010/geoserver/gwc/service/wmts?method=wmts&request=getcapabilities'
        },
        stBase:{
            addForm:stForm + 'addForm',
            deleteForm:stForm + 'deleteForm',
            selectFormItem:stForm + 'selectFormItem',
            selectBoAndAttr:stForm + 'selectBoAndAttr',
            uploadFormItem:stForm + 'uploadFormItem',
            easyInsert:stBase + 'easyInsert',
            easyInsertMul:stBase + 'easyInsertMul',
            easySelect:stBase + 'easySelect',
            easyUpdate:stBase + 'easyUpdate',
            easyDelete:stBase + 'easyDelete',
            easySelectWithPagination:stBase + 'easySelectWithPagination',
            insertAssetsBaseInfo:stBase + 'insertAssetsBaseInfo',
            selectAllGroupAndUser:stBase + 'selectAllGroupAndUser',
            selectGroupUser:stBase + 'selectGroupUser',
            uploadFile:stBase + 'uploadFile',
            insertAssetsUse:stBase + 'insertAssetsUse',
            selectUseDetail:stBase + 'selectUseDetail',
            insertUseDetail:stBase + 'insertUseDetail',
            insertAssetsCheck:stBase + 'insertAssetsCheck',
            selectAssetsCheckDetail:stBase + 'selectAssetsCheckDetail',
            countAssetsByType:stBase + 'countAssetsByType',
            countAssetsByDepartment:stBase + 'countAssetsByDepartment',
            countAssetsByState:stBase + 'countAssetsByState',
            insertPlan:stBase + 'insertPlan',
            selectPlan:stBase + 'selectPlan',
            selectAllPlanAndTask:stBase + 'selectAllPlanAndTask',
            selectAllEvent:stBase + 'selectAllEvent',
            insertEvent:stBase + 'insertEvent',
            selectAllLayers:stBase + 'selectAllLayers'
        },
        stAuth:{
            login:stAuth + 'login',
            getUsersByRole:stAuth + 'getUsersByRole',
            getUsersByRoleAndGroup:stAuth + 'getUsersByRoleAndGroup',
            getUserInfo:stAuth + 'getUserInfo',
            insertUser:stAuth + 'insertUser',
            updateUser:stAuth + 'updateUser',
            selectUser:stAuth + 'selectUser',
            selectRole:stAuth + 'selectRole',
            deleteRole:stAuth + 'deleteRole',
            insertRole:stAuth + 'insertRole',
            updateRole:stAuth + 'updateRole',
            selectMenu:stAuth + 'selectMenu',
            deleteMenu:stAuth + 'deleteMenu',
            insertMenu:stAuth + 'insertMenu',
            updateMenu:stAuth + 'updateMenu',
            selectFun:stAuth + 'selectFun',
            selectFunRole:stAuth + 'selectFunRole',
            deleteFunRole:stAuth + 'deleteFunRole',
            insertFunRole:stAuth + 'insertFunRole',
            selectRoleMenu:stAuth + 'selectRoleMenu',
            deleteRoleMenu:stAuth + 'deleteRoleMenu',
            insertRoleMenu:stAuth + 'insertRoleMenu',
            getCode:stAuth + 'getCode',
            insertGroup:stAuth + 'addGroup',
            // insertGroup:stAuth + 'insertGroup',
            updateGroup:stAuth + 'updateGroup',
            selectGroup:stAuth + 'selectGroup',
            getGroupCode:stAuth + 'getGroupCode',
            selectByGroup:stAuth + 'selectByGroup',
            deleteGroup1:stAuth + 'deleteGroup1',
            insertDic:stAuth + 'insertDic',
            selectDic:stAuth + 'selectDic',
            deleteDic:stAuth + 'deleteDic',
            updateDic:stAuth + 'updateDic',
            addUserRole:stAuth + 'addUserRole',
            selectUserRole:stAuth + 'selectUserRole',
            deleteUserRole:stAuth + 'deleteUserRole',
            updateUserGroup:stAuth + 'updateUserGroup',
            updateUserState:stAuth + 'updateUserState',
            selectDicByParentKey:stAuth + 'selectDicByParentKey',
            selectSubSystem:stAuth + 'selectSubSystem',
			selectSubsystemType:stAuth + 'selectSubsystemType',
            addSubSystem:stAuth + 'addSubSystem',
            updateSubSystem:stAuth + 'updateSubSystem',
            delSubSystem:stAuth + 'delSubSystem',
            selectPosition:stAuth + 'selectPosition',
            addPosition:stAuth + 'addPosition',
            updatePosition:stAuth + 'updatePosition',
            delPosition:stAuth + 'delPosition',
            selectUserOrganize:stAuth + 'selectUserOrganize',
            addUserOrganize:stAuth + 'addUserOrganize',
            updateUserOrganize:stAuth + 'updateUserOrganize',
            delUserOrganize:stAuth + 'delUserOrganize',
            selectGyy:stAuth + 'selectGyy',
            addGyy:stAuth + 'addGyy',
            updateGyy:stAuth + 'updateGyy',
            delGyy:stAuth + 'delGyy',
            selectNotice:stAuth + 'selectNotice',
            addNotice:stAuth + 'addNotice',
            updateNotice:stAuth + 'updateNotice',
            delNotice:stAuth + 'delNotice',
            selectLog:stAuth + 'selectLog',
            addLog:stAuth + 'addLog',
            updateLog:stAuth + 'updateLog',
            delLog:stAuth + 'delLog'
        },
        stFlow:{

        },
        stFlow2:{
            existWorkFlow:stFlow2 + 'existWorkFlow',
            updateWorkFlow:stFlow2 + 'updateWorkFlow',
            createWorkFlow:stFlow2 + 'createWorkFlow',
            deleteWorkFlow:stFlow2 + 'deleteWorkFlow',
            getWorkFlowList:stFlow2 + 'getWorkFlowList',
            getWorkFlowDetail:stFlow2 + 'getWorkFlowDetail',
            updateNodeRoles:stFlow2 + 'updateNodeRoles',
            addLineCond:stFlow2 + 'addLineCond',
            deleteLineCond:stFlow2 + 'deleteLineCond',
            updateLineCond:stFlow2 + 'updateLineCond',
            addNodeForm:stFlow2 + 'addNodeForm',
            deleteNodeForm:stFlow2 + 'deleteNodeForm',
            updateNodeForm:stFlow2 + 'updateNodeForm',
            createCase:stFlow2 + 'createCase',
            withdrawCase:stFlow2 + 'withdrawCase',
            handbackCase:stFlow2 + 'handbackCase',
            deleteCase:stFlow2 + 'deleteCase',
            acceptCase:stFlow2 + 'acceptCase',
            finishCase:stFlow2 + 'finishCase',
            handoverCase:stFlow2 + 'handoverCase',
            handoverToDefault:stFlow2 + 'handoverToDefault',
            handoverToAll:stFlow2 + 'handoverToAll',
            getNodeHandman:stFlow2 + 'getNodeHandman',
            checkStepAutoHandover:stFlow2 + 'checkStepAutoHandover',

            archiveCase:stFlow2 + 'archiveCase' //结束流程
        },
        stMap:{
            getMapPsTc:stMap + 'getMapPsTc',
            getDataPsCg:stMap + 'getDataPsCg',
            insertDataPsCg:stMap + 'insertDataPsCg',
            updateDataPsCg:stMap + 'updateDataPsCg',
            deleteDataPsCg:stMap + 'deleteDataPsCg',
            getDataAllTable:stMap + 'getDataAllTable',
            uploadDataAllTable:stMap + 'uploadDataAllTable',
            selectDataPsfc:stMap + 'selectDataPsfc',
            uploadDataPsfc:stMap + 'uploadDataPsfc',
            selectDataFmc:stMap + 'selectDataFmc',
            deleteDataFmc:stMap + 'deleteDataFmc',
            getDataBurst:stMap + 'getDataBurst',
            easySelect:stMap + 'easySelect',
            easyUpload:stMap + 'easyUpload',
            easyDelete:stMap + 'easyDelete',
            uploadDataBurst:stMap + 'uploadDataBurst',
            queryMapConfigs:stMap + 'queryMapConfigs',
            delMapConfig:stMap + 'delMapConfig',
            addMapConfig:stMap + 'addMapConfig',
            editMapConfig:stMap + 'editMapConfig',
            selectRecordByPlan:stMap + 'selectRecordByPlan',
            selectRecordByPlanParent:stMap + 'selectRecordByPlanParent',
            queryMapPlans:stMap + 'queryMapPlans',
            addMapPlans:stMap + 'addMapPlans',
            editMapPlans:stMap + 'editMapPlans',
            delMapPlans:stMap + 'delMapPlans',
            selectNoPlans:stMap + 'selectNoPlans',
            query:stMap + 'query',
            selectNoPer:stMap + 'queryNoPer',
            addMapPermission:stMap + 'addMapPermission',
            delMapPermission:stMap + 'delMapPermission',
            insertMapRecordPlan:stMap + 'insertMapRecordPlan',
            delMap_Record_Plan:stMap + 'delMap_Record_Plan',
            selectPlanByPer:stMap + 'selectPlanByPer',
            getMyMap:stMap + 'getMyMap'


        },
        stTable:{
            table_bo_def:'zlsk_oms_bo_def',
            table_bo_attr:'zlsk_oms_bo_attr',
            table_data_set:'zlsk_oms_data_set',
            table_bo_tbl:'zlsk_oms_bo_tbl',
            table_data_template:'zlsk_oms_data_tmpl',
            table_data_template_field:'zlsk_oms_data_tmplfield',
            table_data_template_design:'zlsk_oms_data_tmpltpl'
        },
        stForm:{
            addForm:stForm + 'addForm',
            deleteForm:stForm + 'deleteForm',
            selectFormItem:stForm + 'selectFormItem',
            selectBoAndAttr:stForm + 'selectBoAndAttr',
            uploadFormItem:stForm + 'uploadFormItem',
            easyInsert:stForm + 'easyInsert',
            easyInsertMul:stForm + 'easyInsertMul',
            easySelect:stForm + 'easySelect',
            easySelectByOrder:stForm + 'easySelectByOrder',
            easySelectWithOutLike:stForm + 'easySelectWithOutLike',
            easyUpdate:stForm + 'easyUpdate',
            easyDelete:stForm + 'easyDelete',
            easySelectWithPagination:stForm + 'easySelectWithPagination',
            addBo:stForm + 'addBo',
            updateBo:stForm + 'updateBo',
            createBoTable:stForm + 'createBoTable',
            addField:stForm + 'addField',
            updateField:stForm + 'updateField',
            deleteField:stForm + 'deleteField',
            getTemplateFields:stForm + 'getTemplateFields',
            uploadTemplateFields:stForm + 'uploadTemplateFields',

            getDoingCase:stForm + 'getDoingCase',
            getStepHistory:stForm + 'getStepHistory',
            getFlowNodeFormInfo:stForm + 'getFlowNodeFormInfo',
            getDoingCaseByCaseId:stForm + 'getDoingCaseByCaseId',
            getWorkFlowListFilter:stForm + 'getWorkFlowListFilter',
            getCaseInfo:stForm + 'getCaseInfo'
        }
    };
    exports("constantUrl", constantUrl);
});
